package cn.gyyx.core.net.module.user;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GiftsList.proto

public final class GiftsListOuterClass {
  private GiftsListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GiftsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GiftsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */
    int getGiftMapCount();
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */
    boolean containsGiftMap(
            String key);
    /**
     * Use {@link #getGiftMapMap()} instead.
     */
    @Deprecated
    java.util.Map<String, Gift>
    getGiftMap();
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */
    java.util.Map<String, Gift>
    getGiftMapMap();
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */

    Gift getGiftMapOrDefault(
            String key,
            Gift defaultValue);
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */

    Gift getGiftMapOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code GiftsList}
   */
  public  static final class GiftsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GiftsList)
      GiftsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GiftsList.newBuilder() to construct.
    private GiftsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GiftsList() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GiftsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                giftMap_ = com.google.protobuf.MapField.newMapField(
                    GiftMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, Gift>
              giftMap__ = input.readMessage(
                  GiftMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              giftMap_.getMutableMap().put(
                  giftMap__.getKey(), giftMap__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GiftsListOuterClass.internal_static_GiftsList_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetGiftMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GiftsListOuterClass.internal_static_GiftsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GiftsList.class, Builder.class);
    }

    public static final int GIFTMAP_FIELD_NUMBER = 1;
    private static final class GiftMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, Gift> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, Gift>newDefaultInstance(
                  GiftsListOuterClass.internal_static_GiftsList_GiftMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  Gift.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, Gift> giftMap_;
    private com.google.protobuf.MapField<String, Gift>
    internalGetGiftMap() {
      if (giftMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            GiftMapDefaultEntryHolder.defaultEntry);
      }
      return giftMap_;
    }

    public int getGiftMapCount() {
      return internalGetGiftMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */

    public boolean containsGiftMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetGiftMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getGiftMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Gift> getGiftMap() {
      return getGiftMapMap();
    }
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */

    public java.util.Map<String, Gift> getGiftMapMap() {
      return internalGetGiftMap().getMap();
    }
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */

    public Gift getGiftMapOrDefault(
        String key,
        Gift defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Gift> map =
          internalGetGiftMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
     */

    public Gift getGiftMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Gift> map =
          internalGetGiftMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetGiftMap(),
          GiftMapDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, Gift> entry
           : internalGetGiftMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, Gift>
        giftMap__ = GiftMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, giftMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GiftsList)) {
        return super.equals(obj);
      }
      GiftsList other = (GiftsList) obj;

      boolean result = true;
      result = result && internalGetGiftMap().equals(
          other.internalGetGiftMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetGiftMap().getMap().isEmpty()) {
        hash = (37 * hash) + GIFTMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetGiftMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GiftsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GiftsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GiftsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GiftsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GiftsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GiftsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GiftsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GiftsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GiftsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GiftsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GiftsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GiftsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GiftsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GiftsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GiftsList)
        GiftsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GiftsListOuterClass.internal_static_GiftsList_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetGiftMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableGiftMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GiftsListOuterClass.internal_static_GiftsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GiftsList.class, Builder.class);
      }

      // Construct using GiftsListOuterClass.GiftsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableGiftMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GiftsListOuterClass.internal_static_GiftsList_descriptor;
      }

      public GiftsList getDefaultInstanceForType() {
        return GiftsList.getDefaultInstance();
      }

      public GiftsList build() {
        GiftsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GiftsList buildPartial() {
        GiftsList result = new GiftsList(this);
        int from_bitField0_ = bitField0_;
        result.giftMap_ = internalGetGiftMap();
        result.giftMap_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GiftsList) {
          return mergeFrom((GiftsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GiftsList other) {
        if (other == GiftsList.getDefaultInstance()) return this;
        internalGetMutableGiftMap().mergeFrom(
            other.internalGetGiftMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GiftsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GiftsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          String, Gift> giftMap_;
      private com.google.protobuf.MapField<String, Gift>
      internalGetGiftMap() {
        if (giftMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              GiftMapDefaultEntryHolder.defaultEntry);
        }
        return giftMap_;
      }
      private com.google.protobuf.MapField<String, Gift>
      internalGetMutableGiftMap() {
        onChanged();;
        if (giftMap_ == null) {
          giftMap_ = com.google.protobuf.MapField.newMapField(
              GiftMapDefaultEntryHolder.defaultEntry);
        }
        if (!giftMap_.isMutable()) {
          giftMap_ = giftMap_.copy();
        }
        return giftMap_;
      }

      public int getGiftMapCount() {
        return internalGetGiftMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */

      public boolean containsGiftMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetGiftMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getGiftMapMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Gift> getGiftMap() {
        return getGiftMapMap();
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */

      public java.util.Map<String, Gift> getGiftMapMap() {
        return internalGetGiftMap().getMap();
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */

      public Gift getGiftMapOrDefault(
          String key,
          Gift defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Gift> map =
            internalGetGiftMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */

      public Gift getGiftMapOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Gift> map =
            internalGetGiftMap().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearGiftMap() {
        internalGetMutableGiftMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */

      public Builder removeGiftMap(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableGiftMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, Gift>
      getMutableGiftMap() {
        return internalGetMutableGiftMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */
      public Builder putGiftMap(
          String key,
          Gift value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableGiftMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .Gift&gt; giftMap = 1;</code>
       */

      public Builder putAllGiftMap(
          java.util.Map<String, Gift> values) {
        internalGetMutableGiftMap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GiftsList)
    }

    // @@protoc_insertion_point(class_scope:GiftsList)
    private static final GiftsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GiftsList();
    }

    public static GiftsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GiftsList>
        PARSER = new com.google.protobuf.AbstractParser<GiftsList>() {
      public GiftsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GiftsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GiftsList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GiftsList> getParserForType() {
      return PARSER;
    }

    public GiftsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GiftOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Gift)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 chance = 2;</code>
     */
    int getChance();

    /**
     * <code>int32 num = 3;</code>
     */
    int getNum();

    /**
     * <code>string english = 4;</code>
     */
    String getEnglish();
    /**
     * <code>string english = 4;</code>
     */
    com.google.protobuf.ByteString
        getEnglishBytes();

    /**
     * <code>string prizecode = 5;</code>
     */
    String getPrizecode();
    /**
     * <code>string prizecode = 5;</code>
     */
    com.google.protobuf.ByteString
        getPrizecodeBytes();
  }
  /**
   * Protobuf type {@code Gift}
   */
  public  static final class Gift extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Gift)
      GiftOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Gift.newBuilder() to construct.
    private Gift(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Gift() {
      name_ = "";
      chance_ = 0;
      num_ = 0;
      english_ = "";
      prizecode_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Gift(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              chance_ = input.readInt32();
              break;
            }
            case 24: {

              num_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              english_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              prizecode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GiftsListOuterClass.internal_static_Gift_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GiftsListOuterClass.internal_static_Gift_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Gift.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANCE_FIELD_NUMBER = 2;
    private int chance_;
    /**
     * <code>int32 chance = 2;</code>
     */
    public int getChance() {
      return chance_;
    }

    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    /**
     * <code>int32 num = 3;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int ENGLISH_FIELD_NUMBER = 4;
    private volatile Object english_;
    /**
     * <code>string english = 4;</code>
     */
    public String getEnglish() {
      Object ref = english_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        english_ = s;
        return s;
      }
    }
    /**
     * <code>string english = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEnglishBytes() {
      Object ref = english_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        english_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIZECODE_FIELD_NUMBER = 5;
    private volatile Object prizecode_;
    /**
     * <code>string prizecode = 5;</code>
     */
    public String getPrizecode() {
      Object ref = prizecode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        prizecode_ = s;
        return s;
      }
    }
    /**
     * <code>string prizecode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPrizecodeBytes() {
      Object ref = prizecode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        prizecode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (chance_ != 0) {
        output.writeInt32(2, chance_);
      }
      if (num_ != 0) {
        output.writeInt32(3, num_);
      }
      if (!getEnglishBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, english_);
      }
      if (!getPrizecodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, prizecode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (chance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chance_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      if (!getEnglishBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, english_);
      }
      if (!getPrizecodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, prizecode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Gift)) {
        return super.equals(obj);
      }
      Gift other = (Gift) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getChance()
          == other.getChance());
      result = result && (getNum()
          == other.getNum());
      result = result && getEnglish()
          .equals(other.getEnglish());
      result = result && getPrizecode()
          .equals(other.getPrizecode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CHANCE_FIELD_NUMBER;
      hash = (53 * hash) + getChance();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (37 * hash) + ENGLISH_FIELD_NUMBER;
      hash = (53 * hash) + getEnglish().hashCode();
      hash = (37 * hash) + PRIZECODE_FIELD_NUMBER;
      hash = (53 * hash) + getPrizecode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Gift parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gift parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gift parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gift parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gift parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gift parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gift parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Gift parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Gift parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Gift parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Gift parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Gift parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Gift prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Gift}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Gift)
        GiftOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GiftsListOuterClass.internal_static_Gift_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GiftsListOuterClass.internal_static_Gift_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Gift.class, Builder.class);
      }

      // Construct using GiftsListOuterClass.Gift.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        chance_ = 0;

        num_ = 0;

        english_ = "";

        prizecode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GiftsListOuterClass.internal_static_Gift_descriptor;
      }

      public Gift getDefaultInstanceForType() {
        return Gift.getDefaultInstance();
      }

      public Gift build() {
        Gift result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Gift buildPartial() {
        Gift result = new Gift(this);
        result.name_ = name_;
        result.chance_ = chance_;
        result.num_ = num_;
        result.english_ = english_;
        result.prizecode_ = prizecode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Gift) {
          return mergeFrom((Gift)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Gift other) {
        if (other == Gift.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getChance() != 0) {
          setChance(other.getChance());
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (!other.getEnglish().isEmpty()) {
          english_ = other.english_;
          onChanged();
        }
        if (!other.getPrizecode().isEmpty()) {
          prizecode_ = other.prizecode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Gift parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Gift) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int chance_ ;
      /**
       * <code>int32 chance = 2;</code>
       */
      public int getChance() {
        return chance_;
      }
      /**
       * <code>int32 chance = 2;</code>
       */
      public Builder setChance(int value) {
        
        chance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chance = 2;</code>
       */
      public Builder clearChance() {
        
        chance_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <code>int32 num = 3;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>int32 num = 3;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num = 3;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }

      private Object english_ = "";
      /**
       * <code>string english = 4;</code>
       */
      public String getEnglish() {
        Object ref = english_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          english_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string english = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEnglishBytes() {
        Object ref = english_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          english_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string english = 4;</code>
       */
      public Builder setEnglish(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        english_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string english = 4;</code>
       */
      public Builder clearEnglish() {
        
        english_ = getDefaultInstance().getEnglish();
        onChanged();
        return this;
      }
      /**
       * <code>string english = 4;</code>
       */
      public Builder setEnglishBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        english_ = value;
        onChanged();
        return this;
      }

      private Object prizecode_ = "";
      /**
       * <code>string prizecode = 5;</code>
       */
      public String getPrizecode() {
        Object ref = prizecode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          prizecode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string prizecode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPrizecodeBytes() {
        Object ref = prizecode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          prizecode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prizecode = 5;</code>
       */
      public Builder setPrizecode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prizecode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string prizecode = 5;</code>
       */
      public Builder clearPrizecode() {
        
        prizecode_ = getDefaultInstance().getPrizecode();
        onChanged();
        return this;
      }
      /**
       * <code>string prizecode = 5;</code>
       */
      public Builder setPrizecodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        prizecode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Gift)
    }

    // @@protoc_insertion_point(class_scope:Gift)
    private static final Gift DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Gift();
    }

    public static Gift getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Gift>
        PARSER = new com.google.protobuf.AbstractParser<Gift>() {
      public Gift parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Gift(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Gift> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Gift> getParserForType() {
      return PARSER;
    }

    public Gift getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GiftsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GiftsList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GiftsList_GiftMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GiftsList_GiftMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Gift_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Gift_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017GiftsList.proto\"l\n\tGiftsList\022(\n\007giftMa" +
      "p\030\001 \003(\0132\027.GiftsList.GiftMapEntry\0325\n\014Gift" +
      "MapEntry\022\013\n\003key\030\001 \001(\t\022\024\n\005value\030\002 \001(\0132\005.G" +
      "ift:\0028\001\"U\n\004Gift\022\014\n\004name\030\001 \001(\t\022\016\n\006chance\030" +
      "\002 \001(\005\022\013\n\003num\030\003 \001(\005\022\017\n\007english\030\004 \001(\t\022\021\n\tp" +
      "rizecode\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GiftsList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GiftsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GiftsList_descriptor,
        new String[] { "GiftMap", });
    internal_static_GiftsList_GiftMapEntry_descriptor =
      internal_static_GiftsList_descriptor.getNestedTypes().get(0);
    internal_static_GiftsList_GiftMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GiftsList_GiftMapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Gift_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Gift_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Gift_descriptor,
        new String[] { "Name", "Chance", "Num", "English", "Prizecode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
