// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p_module_common.proto

package cn.gyyx.core.net.protocol;

public final class p_module_common {
  private p_module_common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface p_module_common_pingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:p_module_common_ping)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code p_module_common_ping}
   */
  public static final class p_module_common_ping extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:p_module_common_ping)
      p_module_common_pingOrBuilder {
    // Use p_module_common_ping.newBuilder() to construct.
    private p_module_common_ping(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private p_module_common_ping(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final p_module_common_ping defaultInstance;
    public static p_module_common_ping getDefaultInstance() {
      return defaultInstance;
    }

    public p_module_common_ping getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private p_module_common_ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.class, cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.Builder.class);
    }

    public static com.google.protobuf.Parser<p_module_common_ping> PARSER =
        new com.google.protobuf.AbstractParser<p_module_common_ping>() {
      public p_module_common_ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_module_common_ping(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<p_module_common_ping> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code p_module_common_ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:p_module_common_ping)
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_pingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.class, cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.Builder.class);
      }

      // Construct using cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ping_descriptor;
      }

      public cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping getDefaultInstanceForType() {
        return cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.getDefaultInstance();
      }

      public cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping build() {
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping buildPartial() {
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping result = new cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping) {
          return mergeFrom((cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping other) {
        if (other == cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.gyyx.core.net.protocol.p_module_common.p_module_common_ping) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:p_module_common_ping)
    }

    static {
      defaultInstance = new p_module_common_ping(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:p_module_common_ping)
  }

  public interface p_module_common_ackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:p_module_common_ack)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code p_module_common_ack}
   */
  public static final class p_module_common_ack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:p_module_common_ack)
      p_module_common_ackOrBuilder {
    // Use p_module_common_ack.newBuilder() to construct.
    private p_module_common_ack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private p_module_common_ack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final p_module_common_ack defaultInstance;
    public static p_module_common_ack getDefaultInstance() {
      return defaultInstance;
    }

    public p_module_common_ack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private p_module_common_ack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.class, cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.Builder.class);
    }

    public static com.google.protobuf.Parser<p_module_common_ack> PARSER =
        new com.google.protobuf.AbstractParser<p_module_common_ack>() {
      public p_module_common_ack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new p_module_common_ack(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<p_module_common_ack> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code p_module_common_ack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:p_module_common_ack)
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.class, cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.Builder.class);
      }

      // Construct using cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.gyyx.core.net.protocol.p_module_common.internal_static_p_module_common_ack_descriptor;
      }

      public cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack getDefaultInstanceForType() {
        return cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.getDefaultInstance();
      }

      public cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack build() {
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack buildPartial() {
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack result = new cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack) {
          return mergeFrom((cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack other) {
        if (other == cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.gyyx.core.net.protocol.p_module_common.p_module_common_ack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:p_module_common_ack)
    }

    static {
      defaultInstance = new p_module_common_ack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:p_module_common_ack)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p_module_common_ping_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_p_module_common_ping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p_module_common_ack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_p_module_common_ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025p_module_common.proto\"\026\n\024p_module_comm" +
      "on_ping\"\025\n\023p_module_common_ackB,\n\031cn.gyy" +
      "x.core.net.protocolB\017p_module_common"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_p_module_common_ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p_module_common_ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_p_module_common_ping_descriptor,
        new java.lang.String[] { });
    internal_static_p_module_common_ack_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_p_module_common_ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_p_module_common_ack_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
